Ftb 5 : Setup eslint,prettier,husky
canh-nv/nestjs-fresher-training pull request #6
Opened 2024-12-24 10:25 UTC by Duong-N

2024-12-25 07:08 UTC, canhbk requested changes

2024-12-25 07:08 UTC, canhbk commented on .prettierrc
> +  "printWidth": 100,
@Duong-N set printwidth to 80

2024-12-25 07:08 UTC, canhbk commented on .prettierrc
> +  "tabWidth": 2,
@Duong-N use space with 4 size, instead of `tab` for the intent

2024-12-25 07:09 UTC, canhbk commented
Update title of PR to correct format @Duong-N

2024-12-25 09:55 UTC, canhbk requested changes

2024-12-25 09:55 UTC, canhbk commented on .husky/pre-commit
Run lint-staged in this pre-commit

2024-12-25 09:55 UTC, canhbk commented on .prettierrc
> +    "tabWidth": 4,
do we need this `tabWidth` anymore?

2024-12-25 09:55 UTC, canhbk commented on package.json
> +        "*.ts": [
should lint for other file extension as well: js, json, yml, etc

2024-12-25 09:57 UTC, canhbk requested changes

2024-12-25 09:57 UTC, canhbk commented on .eslintrc.js
> +                printWidth: 100,
set printWidth to 80

2024-12-25 09:57 UTC, canhbk commented on .eslintrc.js
> +                printWidth: 100,
should not override prettier config in the eslint

2024-12-25 23:32 UTC, Duong-N commented
![image](https://github.com/user-attachments/assets/71812e73-7f66-41b6-af50-7d5461725789)
Result

2024-12-26 03:23 UTC, canhbk approved these changes

2024-12-26 03:23 UTC, merged